# Включаем поддержку мыши (можно кликать по панелям и скроллить колесиком!)
set -g mouse on

# Увеличиваем историю строк (по дефолту всего 2000, ставим 50000)
set -g history-limit 50000

# Индексация окон с 1, а не с 0 (так удобнее тянуться пальцем на клавиатуре)
set -g base-index 1
setw -g pane-base-index 1

# Быстрое переключение панелей через Alt + стрелочки (без нажатия Ctrl+b)
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Включаем режим vi (ОБЯЗАТЕЛЬНО, чтобы бинды заработали)
setw -g mode-keys vi

# Копирование для Wayland
bind -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy"
bind -T copy-mode MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy"
